# Generated by Django 5.0.4 on 2024-05-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=450)),
                ('second_item_name', models.CharField(max_length=450)),
                ('sum', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
